// get all the pages in src/pages
import { glob } from "glob";
import { execSync } from "node:child_process";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";

// a function to generate a new index.html for each page in src/pages, using the index.html generated by vite build as a template
const generatePage = (path: string) => {
	const template = readFileSync("docs/index.html", "utf-8");
	const pageContent = template.replace(
		`id="root"`,
		`id="root" data-page="${path}"`,
	);

	mkdirSync(`docs/${path}`, { recursive: true });

	writeFileSync(`docs/${path}/index.html`, pageContent);
};

// run build so we have a template index.html to copy for each page
execSync("vite build");

glob.sync("src/pages/**/*.tsx").forEach((file) => {
	const path = file.replace("src/pages/", "").replace(".tsx", "");

	if (path !== "index") {
		generatePage(path);
	}
});
