export type Event = {
	name: string;
	date: Date;
	state: string;
	city: string;
	type: "road" | "trail" | "other";
	distances: string[];
	url: string;
	going: string[];
};

const today = new Date();
today.setHours(0, 0, 0, 0);

const events: Event[] = [
	{
		name: "Wild Goose",
		date: new Date("2026-9-19"),
		state: "NJ",
		city: "Wawayanda State Park",
		type: "trail" as const,
		distances: [
			"36 hours",
			"100 miles",
			"100 km",
			"50 miles",
			"50 km",
			"half marathon",
			"10 km",
		],
		url: "https://www.sassquadtrailrunning.com/wildgoose",
		going: ["Kelly F", "Cam W", "Anna W", "Samson C"],
	},
	{
		name: "Squatchywaska",
		date: new Date("2026-4-25"),
		state: "NY",
		city: "Minnewaska State Preserve",
		type: "trail" as const,
		distances: ["25 km"],
		url: "https://www.sassquadtrailrunning.com/squatchywaska",
		going: ["Emma C"],
	},
	{
		name: "Richmond Marathon",
		date: new Date("2026-11-14"),
		state: "VA",
		city: "Richmond",
		type: "road" as const,
		distances: ["half marathon", "marathon"],
		url: "https://www.richmondmarathon.com/",
		going: ["Kelly F", "Allison D"],
	},
	{
		name: "Big Bear Squatch North",
		date: new Date("2026-4-4"),
		state: "NY",
		city: "Bear Mountain",
		type: "trail" as const,
		distances: ["half marathon", "10 km", "10K Ruck"],
		url: "https://www.sassquadtrailrunning.com/bigbearsquatchnorth",
		going: ["Cam W", "Emma C"],
	},
	{
		name: "YMCA Indoor Triathlon",
		date: new Date("2026-3-8"),
		state: "NY",
		city: "Kingston",
		type: "road" as const,
		distances: ["swim 15 minutes, bike 20 minutes, run 20 minutes"],
		url: "https://www.trisignup.com/Race/NY/Kingston/IndoorTriathlonYMCA",
		going: ["Kelly F", "Rebecca K", "Rosibel L", "Steve S"],
	},
	{
		name: "Jolly January - Club meet up",
		date: new Date("2026-1-18"),
		state: "Kingston NY",
		city: "Union St Brewing Company",
		type: "road" as const,
		distances: ["3pm"],
		url: "https://www.facebook.com/events/2138286426981443/",
		going: ["everyone"],
	},
	{
		name: "Blue Duck Dash - Dan Mawhinney Memorial Winter Series",
		date: new Date("2026-1-25"),
		state: "NY",
		city: "Kingston",
		type: "road" as const,
		distances: ["3.5 miles"],
		url: "https://www.zippy-reg.com/online_reg/index.php?e=2381",
		going: ["Kelly F", "Cam W", "Allison D", "Emma C", "Amanda S", "Todd R"],
	},
	{
		name: "The Keegan Kruiser - Dan Mawhinney Memorial Winter Series",
		date: new Date("2026-2-01"),
		state: "NY",
		city: "Kingston",
		type: "road" as const,
		distances: ["4.1 miles"],
		url: "https://www.zippy-reg.com/online_reg/index.php?e=2381",
		going: ["Kelly F", "Cam W", "Allison D", "Emma C", "Amanda S", "Todd R"],
	},
	{
		name: "The Westkill Krusher - Dan Mawhinney Memorial Winter Series",
		date: new Date("2026-2-08"),
		state: "NY",
		city: "Westkill",
		type: "road" as const,
		distances: ["3.4 miles"],
		url: "https://www.zippy-reg.com/online_reg/index.php?e=2381",
		going: ["Kelly F", "Cam W", "Allison D", "Emma C", "Amanda S", "Todd R"],
	},
	{
		name: "The Union Street Stroll - Dan Mawhinney Memorial Winter Series",
		date: new Date("2026-2-15"),
		state: "NY",
		city: "Kingston",
		type: "road" as const,
		distances: ["3 miles"],
		url: "https://www.zippy-reg.com/online_reg/index.php?e=2381",
		going: ["Kelly F", "Cam W", "Allison D", "Emma C", "Amanda S", "Todd R"],
	},
	{
		name: "Helderberg to Hudson",
		date: new Date("2026-4-11"),
		state: "NY",
		city: "Slingerlands",
		type: "road" as const,
		distances: ["half marathon"],
		url: "https://www.areeventproductions.com/events/areep/h2h/index-main.php",
		going: ["Todd R", "Allison D", "Kelly F"],
	},
	{
		name: "Philidelphia Marathon",
		date: new Date("2026-11-22"),
		state: "PA",
		city: "Philadelphia",
		type: "road" as const,
		distances: ["marathon"],
		url: "https://www.philadelphiamarathon.com",
		going: ["Todd R"],
	},
	{
		name: "Manitou's Revenge",
		date: new Date("2026-6-20"),
		state: "NY",
		city: "Catskills",
		type: "trail" as const,
		distances: ["53 miles"],
		url: "https://www.manitousrevengeultra.com/",
		going: ["Samson C", "Anna W"],
	},
	{
		name: "Hyner Trail Challenge",
		date: new Date("2026-4-18"),
		state: "PA",
		city: "Hyner",
		type: "trail" as const,
		distances: ["50 km", "25 km"],
		url: "https://www.patraildogs.com/hyner",
		going: ["Samson C (waitlist)", "Anna W (waitlist)"],
	},
	{
		name: "English's Ridge Rumble",
		date: new Date("2026-4-18"),
		state: "NY",
		city: "Fayetteville",
		type: "trail" as const,
		distances: ["50 km", "20 mile", "10 mile"],
		url: "https://ultrasignup.com/register.aspx?did=127814",
		going: ["Cam W", "Emma C"],
	},
	{
		name: "Rock The Ridge",
		date: new Date("2026-5-2"),
		state: "NY",
		city: "New Paltz",
		type: "trail" as const,
		distances: ["marathon", "50 mile"],
		url: "https://charity.pledgeit.org/rocktheridge",
		going: ["Todd R"],
	},
	{
		name: "Dirty German Endurance Fest",
		date: new Date("2026-5-9"),
		state: "PA",
		city: "Philadelphia",
		type: "trail" as const,
		distances: ["50 miles", "50 km", "25 km"],
		url: "https://ultrasignup.com/register.aspx?did=128698",
		going: ["Cam W", "Emma C"],
	},
	{
		name: "Annual 5K Run & Walk With The Dogs",
		date: new Date("2026-5-17"),
		state: "NY",
		city: "Beacon",
		type: "road" as const,
		distances: ["5K (dog assisted)"],
		url: "https://runsignup.com/Race/NY/Beacon/ARF5K",
		going: ["Brain K"],
	},
	{
		name: "Amanda's birthday 37 mile challenge",
		date: new Date("2026-3-14"),
		state: "NY",
		city: "Kingston",
		type: "road" as const,
		distances: ["10x 3.7 miles"],
		url: "https://3eleven3.github.io/amanda-run",
		going: ["Amanda S", "Cam W", "Emma C", "Kelly F"],
	},
	// remove events that are in the past
].filter((event) => event.date >= today);

// sort events by date
events.sort((a, b) => a.date.getTime() - b.date.getTime());

export { events };
